version: "3"
services:
  frontend:
    image: frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - "./react-health-dashboard:/react-health-dashboard"
      - "/react-health-dashboard/node_modules"
    ports:
      - 3000:3000
    command: npm start
  backend:
    image: backend
    volumes:
      - ./backendapi:/backend
    ports:
      - 3001:3001
    command: java -jar target/backendapi-0.0.1-SNAPSHOT.jar
    # command: mvn spring-boot:run
